version: "3"
services:
  scheduled-tasks:
    build: .
    image: scheduled-tasks
    container_name: scheduled-tasks
    network_mode: "bridge"
    restart: unless-stopped
    volumes:
      - ./data/:/app/data
